### ISSUE TITLE
IncorrectOperationException: Must not change PSI outside command or undo-transparent action

### ISSUE THREAD

**Issue by dkandalov** [dkandalov/tab-shifter#12]
```
Must not change PSI outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
com.intellij.util.IncorrectOperationException: Must not change PSI outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
	at com.intellij.pom.core.impl.PomModelImpl.b(PomModelImpl.java:361)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:149)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:167)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:699)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:204)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChildInternal(CompositeElement.java:542)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.doReplace(SharedImplUtil.java:211)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.replace(CompositePsiElement.java:212)
	at com.intellij.refactoring.introduceVariable.JavaVariableInplaceIntroducer.deleteTemplateField(JavaVariableInplaceIntroducer.java:169)
	at com.intellij.refactoring.introduceVariable.JavaVariableInplaceIntroducer.deleteTemplateField(JavaVariableInplaceIntroducer.java:67)
	at com.intellij.refactoring.introduce.inplace.AbstractInplaceIntroducer.a(AbstractInplaceIntroducer.java:503)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:934)
	at com.intellij.refactoring.introduce.inplace.AbstractInplaceIntroducer.restoreState(AbstractInplaceIntroducer.java:460)
	at com.intellij.refactoring.introduceParameter.AbstractJavaInplaceIntroducer.restoreState(AbstractJavaInplaceIntroducer.java:104)
	at com.intellij.refactoring.introduceVariable.JavaVariableInplaceIntroducer.performCleanup(JavaVariableInplaceIntroducer.java:161)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring$MyTemplateListener.templateFinished(InplaceRefactoring.java:873)
	at com.intellij.codeInsight.template.impl.TemplateState.f(TemplateState.java:1397)
	at com.intellij.codeInsight.template.impl.TemplateState.c(TemplateState.java:1099)
	at com.intellij.codeInsight.template.impl.TemplateState.gotoEnd(TemplateState.java:1032)
	at com.intellij.codeInsight.template.impl.TemplateState.gotoEnd(TemplateState.java:1036)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl$1.editorReleased(TemplateManagerImpl.java:66)
	at sun.reflect.GeneratedMethodAccessor586.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy35.editorReleased(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:218)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.h(TextEditorComponent.java:186)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.dispose(TextEditorComponent.java:134)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.dispose(PsiAwareTextEditorImpl.java:104)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.dispose(TextEditorImpl.java:79)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:132)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:150)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:136)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:119)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:115)
	at com.intellij.openapi.fileEditor.FileEditorProvider.disposeEditor(FileEditorProvider.java:66)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.disposeComposite(FileEditorManagerImpl.java:1634)
	at com.intellij.openapi.fileEditor.impl.EditorWindow$3.run(EditorWindow.java:244)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runChange(FileEditorManagerImpl.java:1664)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.java:221)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.java:189)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.java:185)
	at tabshifter.Ide.closeCurrentFileIn(Ide.java:49)
	at tabshifter.TabShifter.moveTab(TabShifter.java:80)
	at tabshifter.Actions$ShiftDown.actionPerformed(Actions.java:30)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by dkandalov** [comment]
Can't reproduce anymore.
