### ISSUE TITLE
PluginException OSX 

### ISSUE THREAD

**Issue by bitwes** [dkandalov/tab-shifter#18]
I get the following exception immediately after installing.  The plugin has always been greyed out (disabled) in the menus but is enabled in the settings.  I'm new to IntelliJ so it took me a little while to notice the "!" in the bottom right hand corner which led me to the "IDE Fatal Errors" dialog.  There are no other errors listed for the IDE and I have no other plugins installed.  The only customizations I've done is change my key bindings.

MacBook Pro (mid 2014)
JRE:  1.8.0_152
JVM:  Open JDK 64 bit server by Jetbrains
IntelliJ version:  2018.2.2 (Community Edition)
OSX version: 10.11.6 

```
com.intellij.diagnostic.PluginException: tabshifter.Actions$StretchRight PluginClassLoader[socrates.tabshifter, 0.26] com.intellij.ide.plugins.cl.PluginClassLoader@3af27870 [Plugin: socrates.tabshifter]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:144)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:458)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:446)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1266)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: tabshifter.Actions$StretchRight PluginClassLoader[socrates.tabshifter, 0.26] com.intellij.ide.plugins.cl.PluginClassLoader@3af27870
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:140)
	... 19 more
```

**Comment by dkandalov** [comment]
From the stacktrace it looks like the version of the plugin is 0.26 which I never released (see https://plugins.jetbrains.com/plugin/7475-tab-shifter)

I tried version 0.25 in the following version and couldn't reproduce the problem.

IntelliJ IDEA 2018.2.2 (Community Edition)
Build #IC-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by bitwes** [comment]
It works now, I'm not sure why but I did install it differently this time.  For both of my previous installs I downloaded the zip from github and installed it from a local file.  Today, I Fixed my proxy settings in the IDE and installed from the "repository" via the IDE.  That seems to have done it.  Tabs move now, and I'm happy.  Nice plugin.
